version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec rails s -b "0.0.0.0"
    container_name: web
    ports:
      - 3000:3000
    env_file: .env
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:8.1.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: db
    volumes:
      - db-volume:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  db-volume:
