version: 2.1

defaults: &defaults
  working_directory: ~/detect_readonly_sql
  docker:
    - image: cimg/ruby:3.1.2
      environment:
        RAILS_ENV: test
    - image: cimg/mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: password

jobs:
  rspec:
    <<: *defaults
    steps:
      - checkout
      - run: bundle install -j4
      - run: bundle exec rspec

workflows:
  version: 2
  prepare_and_test:
    jobs:
      - rspec
